testcafe_tests:
  stage: test
  image: node:18.16.0-bullseye-slim
  before_script:
    # Install required packages and tools
    - apt-get update
    - apt-get install --no-install-recommends -y yarn

    # install latest versions of npm and node-gyp
    - npm install -g npm
    - npm install -g node-gyp

    # Install yarn
    - npm install -g yarn
  script:
    - yarn install
    - yarn testcafe chrome:headless tests/sampleTest.ts -e -c 10
  artifacts:
    paths:
      - $CI_PROJECT_DIR
    when: on_failure
    expire_in: 5 days