testcafe_tests:
  stage: test
  image: centos
  before_script:
    - dnf -y install wget zip jq
    - dnf -y module install nodejs:12
    - npm install -g yarn
    - dnf -y install snapd
    - systemctl enable --now snapd.socket
    - ln -s /var/lib/snapd/snap /snap
    - snap install firefox
  script:
    - yarn install
    - yarn testcafe firefox:headless tests/sampleTest.js -e
  artifacts:
    paths:
      - tests/results
    reports:
      junit: tests/results/report.xml
