testcafe_tests:
  stage: test
  image: centos
  before_script:
    - dnf -y install wget zip jq
    - dnf -y module install nodejs:12
    - npm install -g yarn
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    - dnf -y install google-chrome-stable_current_x86_64.rpm
  script:
    - yarn install
    - yarn testcafe firefox:headless tests/sampleTest.js -e
  artifacts:
    paths:
      - tests/results
    reports:
      junit: tests/results/report.xml
