image: node:latest
  
  variables:
      BROWSERSTACK_USE_AUTOMATE: "1"
      BROWSERSTACK_USERNAME: "ayemelyanenko1"
      BROWSERSTACK_ACCESS_KEY: "ADXbZBpxzvNepuUzg9mz"
      BROWSERSTACK_DISPLAY_RESOLUTION: "1600x1200"
      BROWSERSTACK_DEBUG: "true"
  
  before_script:
    - yarn install --frozen-lockfile
  
  job1: 
    script:
        - yarn testcafe "browserstack:chrome:OS X Catalina" ./tests/sampleTest.js -e -q
    allow_failure: true
  
  job2:
    script:
        - yarn testcafe "browserstack:firefox:OS X Catalina" ./tests/sampleTest.js -e -q
    allow_failure: true